#!/usr/bin/env bash
#
# Instala o gerenciador server-web
#
# Por oliver, 2024
#
#

install() {
  echo -e "\e[2;32mInstalando pacotes...\e[0m"
  apt update && apt upgrade -y
  apt install git -y
  echo -e "\e[2;32mInstalando pacotes... Done\e[0m"

  [ -d $HOME/Server-Web ] && rm -rf $HOME/Server-Web

  echo -e "\e[2;32mClonando repositório server-web...\e[0m"
  git clone https://github.com/Olliv3r/Server-Web $HOME/Server-Web > /dev/null 2>&1
  echo -e "\e[2;32mClonando repositório server-web...\e[0m"
  cd $HOME/Server-Web
  bash ./setup
}

install
